const puppeteer = require('puppeteer');
const path = require('path');
const fs = require('fs');

const generateInvoicePDF = async (invoice, organization) => {
  const outputDir = path.join(__dirname, '..', 'uploads', 'invoices');
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  const filePath = path.join(outputDir, `invoice-${invoice.invoice_number}.pdf`);

  const itemsHTML = invoice.items
    .map(
      (item, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${item.description}</td>
        <td>${item.quantity}</td>
        <td>${org.currency} ${item.unit_price.toFixed(2)}</td>
        <td>${org.currency} ${item.line_total.toFixed(2)}</td>
      </tr>`
    )
    .join('');

  const org = organization || {};
  const client = invoice.client || {};

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 30px; }
    .logo img { max-height: 80px; }
    .org-info h1 { margin: 0; font-size: 24px; color: #2563eb; }
    .invoice-title { text-align: right; }
    .invoice-title h2 { font-size: 36px; color: #2563eb; margin: 0; }
    .invoice-title p { margin: 4px 0; font-size: 13px; color: #666; }
    .section { display: flex; justify-content: space-between; margin: 20px 0; }
    .bill-to h4, .invoice-meta h4 { color: #2563eb; font-size: 12px; text-transform: uppercase; margin-bottom: 6px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { background: #2563eb; color: white; padding: 10px 8px; text-align: left; font-size: 13px; }
    td { padding: 9px 8px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
    tr:nth-child(even) td { background: #f9fafb; }
    .totals { margin-top: 20px; text-align: right; }
    .totals table { width: 300px; margin-left: auto; }
    .totals td { border: none; padding: 5px 8px; }
    .totals .grand-total td { font-weight: bold; font-size: 16px; color: #2563eb; border-top: 2px solid #2563eb; }
    .footer { margin-top: 50px; text-align: center; font-size: 11px; color: #9ca3af; }
    .status-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold;
      background: ${invoice.status === 'Paid' ? '#dcfce7' : invoice.status === 'Overdue' ? '#fee2e2' : '#fef9c3'};
      color: ${invoice.status === 'Paid' ? '#166534' : invoice.status === 'Overdue' ? '#991b1b' : '#713f12'};
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="org-info">
      ${org.logo_url ? `<div class="logo"><img src="${org.logo_url}" /></div>` : ''}
      <h1>${org.name || 'Your Company'}</h1>
      <p>${org.address || ''}</p>
      <p>${org.email || ''} | ${org.phone || ''}</p>
      ${org.tax_id ? `<p>Tax ID: ${org.tax_id}</p>` : ''}
    </div>
    <div class="invoice-title">
      <h2>INVOICE</h2>
      <p><strong>#${invoice.invoice_number}</strong></p>
      <p>Status: <span class="status-badge">${invoice.status}</span></p>
      <p>Issue Date: ${new Date(invoice.issue_date).toLocaleDateString()}</p>
      ${invoice.due_date ? `<p>Due Date: ${new Date(invoice.due_date).toLocaleDateString()}</p>` : ''}
    </div>
  </div>

  <div class="section">
    <div class="bill-to">
      <h4>Bill To</h4>
      <p><strong>${client.companyName || ''}</strong></p>
      <p>${client.contactPerson || ''}</p>
      <p>${client.email || ''}</p>
      <p>${client.phone || ''}</p>
      <p>${client.address || ''}</p>
    </div>
  </div>

  <table>
    <thead>
      <tr><th>#</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>
    </thead>
    <tbody>${itemsHTML}</tbody>
  </table>

  <div class="totals">
    <table>
      <tr><td>Subtotal:</td><td>${org.currency || 'CAD'} ${invoice.subtotal.toFixed(2)}</td></tr>
      <tr><td>Tax (${invoice.tax_rate}% GST/HST):</td><td>${org.currency || 'CAD'} ${invoice.tax_amount.toFixed(2)}</td></tr>
      <tr class="grand-total"><td>Grand Total:</td><td>${org.currency || 'CAD'} ${invoice.total_amount.toFixed(2)}</td></tr>
    </table>
  </div>

  ${invoice.notes ? `<div style="margin-top:30px;"><h4>Notes</h4><p>${invoice.notes}</p></div>` : ''}

  <div class="footer">
    <p>Thank you for your business! | Generated by CRM System</p>
  </div>
</body>
</html>`;

  const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });
  await page.pdf({ path: filePath, format: 'A4', printBackground: true, margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' } });
  await browser.close();

  return filePath;
};

module.exports = { generateInvoicePDF };
